#!/usr/bin/env ruby
# -*- coding:utf-8 -*-

require 'optparse'

solver :Ruby, :rb
solver :Python, :py do ['python3 -u', 'python -u'] end
solver :Lua
solver :Squirrel,   :nut, 'sq'
solver :Julia,      :jl
solver :Javascript, :js,  'node'

solver :Typescript, :ts do |l|
  "tsc --target es2019 --module commonjs --strict #{l.src} &&
     node #{l.src.sub(/\.ts$/, ".js")} #{l.o} "
end

solver :Perl, :pl
solver :Php
solver :Groovy

solver :Awk do |l|
  awk = select_cmd( "gawk", "awk" )
  "#{awk} -f #{l.src} -- #{l.o}"
end

solver :C do |l|
  cc = select_cmd( "clang", "gcc" )
  "#{cc} -o #{l.src}.out -O2 -Wall #{l.src} && ./#{l.src}.out #{l.o}"
end

solver :'C++', :cpp do |l|
  cc = select_cmd( "clang++", "g++" )
  "#{cc} -o #{l.src}.out -O2 -Wall -std=c++17 #{l.src} && ./#{l.src}.out #{l.o}"
end

solver :'C#', :cs do |l|
  mono = exists?( "mono" ) ? "mono" : ''
  csc  = select_cmd( "mcs", "csc" )
  "#{csc} -nologo -optimize+ -out:#{l.src}.out #{l.src} &&
     #{mono} ./#{l.src}.out #{l.o}"
end

solver :Java do |l|
  "javac -d build #{l.src} &&
     java -cp build #{l.src.sub(/\.\w+$/, '')} #{l.o}"
end

solver :Kotlin, :kt do |l|
  "kotlinc #{l.src} -include-runtime -d solver.jar &&
     kotlin solver.jar #{l.o}"
end

solver :Go,  'go run'

solver :Rust, :rs do |l|
  [ "rust-script #{l.src} #{l.o}",
    "rustc -O -o #{l.src}.out #{l.src} &&  ./#{l.src}.out #{l.o}" ]
end

solver :Swift do |l|
  [ "swiftc -Ounchecked -o #{l.src}.out #{l.src} &&  ./#{l.src}.out #{l.o}",
    "swift #{l.src} #{l.o}" ]
end

solver :Lisp do |l|
  [ "sbcl --script #{l.src} #{l.o}",
    "clisp -q -c #{l.src} -o #{l.src}.fas &&  clisp #{l.src}.fas #{l.o}" ]
end

solver :Crystal, :cr do |l|
  "crystal build --release -o #{l.src}.out #{l.src} &&  ./#{l.src}.out #{l.o}"
end

solver :Elixir, :exs

solver :'F#', :fsx do |l|
  [ "fsi --optimize+ #{l.src} #{l.o}",
    "fsc --optimize+ -o #{l.src}.out #{l.src} &&  ./#{l.src}.out #{l.o}",
    "dotnet fsi --optimize+ #{l.src} #{l.o}" ]
end

###########################################################

BEGIN {
  LANG_DEF = {}
  Lang     = Struct.new( 'Lang', :name, :ext, :prog, :src, :o )

  def solver lang, *arg, &block
    arg.unshift(nil)  unless arg[0].is_a?(Symbol)   # ext
    ext  = arg[0] || lang.to_s.downcase
    prog = block_given? ? block : Proc.new{ (arg[1] || lang.to_s.downcase) }
    src  = case lang
           when :Java;       "Solver.#{ext}"
           when :Typescript; "solver-ts.#{ext}"
           else              "solver.#{ext}"
           end
    LANG_DEF[ lang ] = Lang.new( lang, ext.to_s, prog, src )
  end
}

###########################################################

def options
  $O = {compile: true}

  exit(1) unless ARGV.options{|opt|
    opt.banner =<<EOT
Usage:  #{File.basename(__FILE__)} OPTION... ext...
    Execute PENTOMINO Solvers written in various programming languages.

    Lang/ext:
#{    LANG_DEF.values.sort_by{ |lang| lang.name }.
        each_with_object( [[]] ) do |lang,lines|
          lines[-1] << "#{lang.name}/#{lang.ext}"
          lines << [lines[-1].pop]  if lines[-1].join( ', ' ).size > 60
        end.map { |words| '      ' + words.join( '  ' ) }.join( "\n" )
}

    ex: ./run-solver --size 8x8 ruby py
        # ruby solver.rb 8x8
        # python3 solver.py 8x8

EOT
    opt.on( '-a', '--all',  "execute all languages" )
    opt.on( '-s', '--size=WxH' ) { |v| v =~ /^\d+x\d+$/ ? v : nil }
    opt.on( '-d', '--debug', "execute with '--debug'" )
    opt.on( '-n', '--suppress' )
    opt.on( '--[no-]compile' )

    r = opt.parse!( into: $O )
    if ARGV.empty? && !$O[:all]
      puts opt.help
      exit
    end
    r
  }
end

###########################################################

def exists?( bin )
  %x[ type #{bin} > /dev/null 2>&1 ]
  $? == 0
end

def select_cmd( *progs )
  progs.select{ |prg| exists?( prg.split[0] ) }[0] || progs[-1]
end

def run( *cmds )
  cmds.each do |cmd|
    puts "    #{cmd}"
    bin = cmd.split[0]
    if ! exists?( bin )
      puts "    #{bin} doesn't exist."
      return true
    elsif $O[:suppress] == nil
      # swap stdout with stderr
      #   stderr:  output of solver
      #   stdout:  output of time command
      IO.popen( "bash -c 'time #{cmd}' 3>&1 1>&2 2>&3", "r+" ) do |io|
        while !io.eof
          puts io.gets
        end
      end
      return false  if $? != 0
    end # if
  end # each
  return true
end

###########################################################

def main()
  options()

  args = $O[:all] ?
            LANG_DEF.values.map { |lang| lang.ext } :
            ARGV.map{ |s| s }

  args.each do |arg|
    lang = LANG_DEF.values.find{ |lang|
      lang.name.to_s.upcase == arg.upcase || lang.ext == arg
    }
    if lang.nil?
      puts "#{arg}? skip it"
      next
    end

    lang.o = [ $O[:debug] ? "--debug" : "", $O[:size].to_s ].join( " " ).strip

    puts "== #{lang.name} =="
    case result = lang.prog.call( lang )
    when String, Array
      cmd  = select_cmd( *result )
      cmd  = "#{cmd} #{lang.src} #{lang.o}"  if cmd !~/#{lang.src}/
      cmds = cmd.split( '&&' ).map{ |c| c.gsub(/\s+/, ' ').strip }
      cmds.shift  if cmds.size > 1 && $O[:compile] == false
      result = run *cmds
    end
    puts "#{lang.name}: failed\n"  unless result
  end # args

end

begin
  $stdout.sync = true
  main
rescue Interrupt
  puts "Interrupted"
rescue Errno::EPIPE
  puts $!
rescue
  puts $!.class
  puts $!
  puts $!.backtrace
end
